---
- name: Redirect root URL to nagiosxi
  become: true
  ansible.builtin.lineinfile:
    path: /etc/httpd/conf.d/nagiosxi.conf
    line: "RedirectMatch ^/$ /nagiosxi/"
    regexp: '^RedirectMatch \^/\$'
    insertbefore: BOF
  notify: Reload nagiosxi web server

- name: Generate nagios xi configuration from CCM
  become: true
  ansible.builtin.command:
    cmd: /usr/local/nagiosxi/scripts/reconfigure_nagios.sh
  changed_when: false

- name: Ensure nagios xi services are started and enabled
  become: true
  ansible.builtin.service:
    name: "{{ __nagiosxi_service }}"
    state: started
    enabled: true
  loop:
    - "{{ nagiosxi_apache_services[ansible_facts['os_family']] }}"
    - nagios
  loop_control:
    loop_var: __nagiosxi_service

- name: Wait for nagios xi web interface
  ansible.builtin.wait_for:
    port: 80
    timeout: 120
