---
- name: Install nagios xi
  ansible.builtin.import_tasks: install.yml
  tags:
    - nagiosxi
    - nagiosxi-install

- name: Check the nagios xi setup wizard
  ansible.builtin.import_tasks: wizard.yml
  tags:
    - nagiosxi
    - nagiosxi-install
    - nagiosxi-config

- name: Configure nagios xi services
  ansible.builtin.import_tasks: config.yml
  tags:
    - nagiosxi
    - nagiosxi-config
